name: "Build and Test"
on: [push, pull_request]

jobs:
  build-source:
    name: "Build Source Code"
    runs-on: ubuntu-latest
    env:
      JDK_VER: 17
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v2
      - name: "Set up JDK 17"
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: "build"
        run: |
          mvn clean && mvn verify
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}